### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by bryant1410** [m-bain/frozen-in-time#16]
More often than not, I'm getting the following exception while training (e.g., training on MSR-VTT):

```
Exception in thread QueueFeederThread:
Traceback (most recent call last):
  File "***/miniconda3/envs/frozen/lib/python3.7/multiprocessing/queues.py", line 232, in _feed
    close()
  File "***/miniconda3/envs/frozen/lib/python3.7/multiprocessing/connection.py", line 177, in close
    self._close()
  File "***/miniconda3/envs/frozen/lib/python3.7/multiprocessing/connection.py", line 361, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "***/miniconda3/envs/frozen/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "***/miniconda3/envs/frozen/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "***/miniconda3/envs/frozen/lib/python3.7/multiprocessing/queues.py", line 263, in _feed
    queue_sem.release()
ValueError: semaphore or lock released too many times
```

Do you have any idea of what's going on?

The training still continues and finishes (reporting repeated errors), not sure if it trains fine though.

**Comment by bryant1410** [comment]
Just to give more details, after that I get similar "Bad file descriptor" errors but also the following one repeated times:

```
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f3c8486f7a0>
Traceback (most recent call last):
  File "***/miniconda3/envs/frozen/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "***/miniconda3/envs/frozen/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "***/miniconda3/envs/frozen/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
```

**Comment by m-bain** [comment]
Can you try reducing num_workers in the config file? I think I've encountered something similar, my hunch is that the cv2 video reader is spawning lots of processes or using more cpus than allocated somehow -- reducing num_workers might be a cheap workaround
